import React, { useState } from 'react';
import { View, Text, Pressable, StyleSheet, useWindowDimensions, ScrollView } from 'react-native';
import { Slot, Redirect, router, usePathname } from 'expo-router';
import { useAuth } from '@/src/auth-context';
import { colors, fonts } from '@/src/theme';
import { Screen, Icon, IconButton, Sheet, Notice, Loading, s } from '@/src/components/ui';

const navigation = [['/admin', 'Overview', 'grid-outline'], ['/admin/buses', 'Buses & layouts', 'bus-outline'], ['/admin/routes', 'Routes', 'git-branch-outline'], ['/admin/trips', 'Schedules & trips', 'calendar-outline'], ['/admin/staff', 'Drivers & staff', 'people-outline'], ['/admin/offers', 'Offers & coupons', 'pricetag-outline'], ['/admin/support', 'Support inbox', 'chatbubbles-outline'], ['/admin/audit', 'Activity & audit', 'shield-checkmark-outline']];
export default function AdminLayout() {
  const { user, loading, logout } = useAuth();
  const { width } = useWindowDimensions();
  const path = usePathname();
  const [open, setOpen] = useState(false);
  const [error, setError] = useState('');
  if (loading) return <Loading />;
  if (!user || !['admin', 'super_admin'].includes(user.role)) return <Redirect href="/admin-login" />;
  const navigate = (url: string) => { setOpen(false); router.push(url as any); };
  const signOut = async () => { try { await logout(); router.replace('/admin-login'); } catch (e: any) { setError(e.message); } };
  const menu = <><View style={styles.identity}><Text style={s.overline}>OPERATIONS WORKSPACE</Text><Text style={s.bodyStrong}>{user.name}</Text><Text style={s.caption}>{user.role === 'super_admin' ? 'Super Administrator' : 'Administrator'}</Text></View>{navigation.map(([url, title, icon]) => <Pressable key={url} testID={`admin-nav-${title.toLowerCase().replaceAll(' ', '-').replaceAll('&', 'and')}`} onPress={() => navigate(url)} style={[styles.nav, path === url && styles.navActive]}><Icon name={icon} size={20} color={path === url ? colors.brand : colors.muted} /><Text style={[styles.navText, path === url && { color: colors.brand, fontWeight: '700' }]}>{title}</Text></Pressable>)}<View style={s.divider} /><Notice message={error} /><Pressable testID="admin-logout-button" style={styles.nav} onPress={signOut}><Icon name="log-out-outline" /><Text style={styles.navText}>Sign out</Text></Pressable></>;
  return <Screen><View style={styles.top}><View style={s.row}>{width < 800 && <IconButton name="menu-outline" testID="admin-menu-button" onPress={() => setOpen(true)} />}<View style={styles.logo}><Icon name="bus" size={22} color={colors.onBrand} /></View><Text style={styles.brand}>GoBus<Text style={{ color: colors.brandSecondary }}>.</Text></Text><View style={styles.adminTag}><Text style={styles.adminTagText}>ADMIN</Text></View></View><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.slice(0, 1)}</Text></View></View><View style={styles.main}>{width >= 800 && <ScrollView style={styles.sidebar} contentContainerStyle={{ padding: 18, gap: 7 }}>{menu}</ScrollView>}<View style={styles.slot}><Slot /></View></View><Sheet title="Workspace" visible={open} onClose={() => setOpen(false)}>{menu}</Sheet></Screen>;
}
const styles = StyleSheet.create({ top: { height: 72, paddingHorizontal: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, logo: { width: 34, height: 34, borderRadius: 11, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, brand: { fontFamily: fonts.heading, fontSize: 23, fontWeight: '800', color: colors.onSurface, letterSpacing: -1 }, adminTag: { padding: 6, backgroundColor: colors.surfaceSecondary, borderRadius: 5 }, adminTagText: { fontFamily: fonts.body, fontSize: 8, letterSpacing: 1, fontWeight: '700', color: colors.muted }, avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.brandTertiary, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.brand, fontFamily: fonts.body, fontWeight: '700' }, main: { flex: 1, flexDirection: 'row' }, sidebar: { width: 245, flexGrow: 0, borderRightWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, slot: { flex: 1 }, identity: { padding: 14, gap: 8, marginBottom: 12 }, nav: { flexDirection: 'row', alignItems: 'center', minHeight: 50, gap: 12, borderRadius: 12, paddingHorizontal: 14 }, navActive: { backgroundColor: colors.brandTertiary }, navText: { fontFamily: fonts.body, color: colors.onSurfaceSecondary, fontSize: 13 } });