import { useState } from 'react';
import { ScrollView, Pressable, Text, View, StyleSheet } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/src/auth-context';
import { colors, fonts } from '@/src/theme';
import { Screen, Header, Icon, Card, Button, Badge, Notice, Section, s } from '@/src/components/ui';

export default function Profile() {
  const { user, logout } = useAuth(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const signOut = async () => { setBusy(true); try { await logout(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  return <Screen bottom={false}><Header title="Your corner of GoBus" subtitle="A more personal way to travel." /><ScrollView contentContainerStyle={s.content}><Notice message={error} /><Card><View style={styles.avatar}><Text style={styles.initial}>{user ? user.name[0].toUpperCase() : 'G'}</Text></View><Text style={s.h1}>{user ? user.name : 'Hello, traveller.'}</Text><Text style={s.body}>{user ? user.email : 'Your trips, details and support.\nAll together, wherever you go.'}</Text>{user ? <><Badge title="PASSENGER ACCOUNT" /><View style={s.divider} /><Text style={s.caption}>MOBILE NUMBER</Text><Text testID="profile-mobile" style={s.bodyStrong}>{user.mobile}</Text><Text style={s.caption}>{user.mobile_verified ? 'Verified' : 'Not verified · SMS verification is not configured yet.'}</Text></> : <Button title="Sign in or create an account" testID="profile-sign-in-button" onPress={() => router.push('/sign-in')} />}</Card><Section title="Here to help" /><Pressable testID="profile-support-button" style={styles.menu} onPress={() => router.push('/support')}><View style={styles.menuIcon}><Icon name="chatbubbles-outline" /></View><View style={s.flex}><Text style={s.bodyStrong}>Help & support</Text><Text style={s.caption}>FAQs and your support requests</Text></View><Icon name="chevron-forward" size={18} /></Pressable>{user && <Button title="Sign out" testID="passenger-logout-button" secondary onPress={signOut} loading={busy} />}{!user && <><Section title="GoBus for operators" /><Text style={s.body}>Dedicated workspaces. Separate permissions.</Text><Pressable testID="open-admin-login-button" style={styles.menu} onPress={() => router.push('/admin-login')}><Icon name="grid-outline" /><View style={s.flex}><Text style={s.bodyStrong}>Admin workspace</Text><Text style={s.caption}>Manage your network</Text></View><Icon name="arrow-forward" size={18} /></Pressable><Pressable testID="open-driver-login-button" style={styles.menu} onPress={() => router.push('/driver-login')}><Icon name="speedometer-outline" /><View style={s.flex}><Text style={s.bodyStrong}>Driver / in-bus</Text><Text style={s.caption}>Your assigned journeys</Text></View><Icon name="arrow-forward" size={18} /></Pressable></>}<Text style={[s.caption, s.center]}>GoBus · A better way to get there.</Text></ScrollView></Screen>;
}
const styles = StyleSheet.create({ avatar: { width: 66, height: 66, borderRadius: 23, backgroundColor: colors.brandTertiary, alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 28, color: colors.brand, fontFamily: fonts.heading, fontWeight: '700' }, menu: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 18, borderWidth: 1, borderColor: colors.border, borderRadius: 18, backgroundColor: colors.surface }, menuIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.brandTertiary, alignItems: 'center', justifyContent: 'center' } });