import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, fonts } from '@/src/theme';
import { Chips, Icon, s } from './ui';

export type LayoutSeat = { id: string; label: string; deck: string; row: number; col: number; row_span: number; col_span: number; type: string; price: number; status: string; ladies: boolean };
export type BusLayout = { rows: number; columns: number; decks: string[]; seats: LayoutSeat[] };
const CELL = 48;
export function SeatMap({ layout, states = {}, selected = [], onSeat, editor = false, onCell }: { layout: BusLayout; states?: Record<string, string>; selected?: string[]; onSeat?: (seat: LayoutSeat) => void; editor?: boolean; onCell?: (row: number, col: number, deck: string) => void }) {
  const [deck, setDeck] = useState('lower');
  const actualDeck = layout.decks.includes(deck) ? deck : layout.decks[0];
  return <View testID="physical-seat-layout" style={{ gap: 12 }}><Chips values={layout.decks.map(d => d === 'lower' ? 'Lower deck' : 'Upper deck')} value={actualDeck === 'lower' ? 'Lower deck' : 'Upper deck'} onChange={v => setDeck(v === 'Lower deck' ? 'lower' : 'upper')} testID="deck-selector" /><ScrollView horizontal showsHorizontalScrollIndicator={layout.columns > 6} contentContainerStyle={{ flexGrow: 1, justifyContent: 'center', padding: 8 }}><View style={styles.bus}><View style={styles.front}><Text style={s.overline}>FRONT OF BUS</Text></View><View style={{ width: layout.columns * CELL, height: layout.rows * CELL }}>
    {editor && Array.from({ length: layout.rows }, (_, row) => Array.from({ length: layout.columns }, (_, col) => <Pressable testID={`layout-cell-${actualDeck}-${row}-${col}`} key={`${row}-${col}`} onPress={() => onCell?.(row, col, actualDeck)} style={[styles.cell, { top: row * CELL, left: col * CELL }]}><Icon name="add" size={13} color={colors.borderStrong} /></Pressable>))}
    {layout.seats.filter(seat => seat.deck === actualDeck).map(seat => { const state = states[seat.id] || seat.status; const chosen = selected.includes(seat.id); const disabled = !editor && (seat.type === 'driver' || seat.type === 'aisle' || state !== 'AVAILABLE'); return <Pressable testID={`seat-${seat.id}`} accessibilityLabel={`${seat.type} ${seat.label}, ${state}${seat.ladies ? ', ladies reserved' : ''}`} key={seat.id} disabled={disabled || !onSeat} onPress={() => onSeat?.(seat)} style={({ pressed }) => [styles.seat, { top: seat.row * CELL + 2, left: seat.col * CELL + 2, width: seat.col_span * CELL - 4, height: seat.row_span * CELL - 4 }, seat.type === 'aisle' && styles.aisle, seat.type === 'driver' && styles.driver, ['BLOCKED', 'INACTIVE', 'SOLD', 'LOCKED'].includes(state) && styles.unavailable, chosen && styles.selected, pressed && s.pressed]}>{seat.type === 'driver' ? <Icon name="speedometer-outline" size={23} color={colors.onSurfaceSecondary} /> : seat.type === 'aisle' ? (editor ? <Text style={styles.aisleText}>Aisle</Text> : null) : <><Text numberOfLines={1} style={[styles.seatText, chosen && { color: colors.onBrand }, disabled && { color: colors.muted }]}>{seat.label}</Text>{seat.ladies && <Text style={[styles.ladies, chosen && { color: colors.onBrand }]}>L</Text>}<View style={[styles.seatEdge, chosen && { borderColor: colors.onBrand }, seat.type === 'berth' && styles.berthEdge]} /></>}</Pressable>; })}
  </View><View style={styles.rear}><Text style={s.caption}>{editor ? 'Tap an empty cell to place an element' : 'Exact operator-configured floor plan'}</Text></View></View></ScrollView>{!editor && <View style={styles.legend}>{[['Available', colors.surface, colors.brandSecondary], ['Selected', colors.brand, colors.brand], ['Unavailable', colors.surfaceTertiary, colors.borderStrong]].map(([label, fill, border]) => <View key={label} style={{ flexDirection: 'row', gap: 5, alignItems: 'center' }}><View style={{ width: 12, height: 12, borderRadius: 3, backgroundColor: fill, borderWidth: 1, borderColor: border }} /><Text style={s.caption}>{label}</Text></View>)}</View>}</View>;
}
const styles = StyleSheet.create({ bus: { borderWidth: 1, borderColor: colors.borderStrong, borderRadius: 26, padding: 12, backgroundColor: colors.surface }, front: { height: 44, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1, borderColor: colors.border, marginBottom: 12 }, rear: { minHeight: 36, alignItems: 'center', justifyContent: 'center', marginTop: 10 }, cell: { position: 'absolute', width: CELL, height: CELL, borderWidth: 0.5, borderStyle: 'dashed', borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, seat: { position: 'absolute', borderWidth: 1, borderColor: colors.brandSecondary, borderRadius: 7, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', paddingBottom: 4 }, seatText: { fontFamily: fonts.body, fontSize: 11, fontWeight: '700', color: colors.brand }, seatEdge: { position: 'absolute', bottom: 4, width: '72%', height: 5, borderWidth: 1, borderColor: colors.brandSecondary, borderRadius: 3 }, berthEdge: { bottom: 7, height: 11 }, selected: { backgroundColor: colors.brand, borderColor: colors.brand }, unavailable: { backgroundColor: colors.surfaceTertiary, borderColor: colors.borderStrong }, aisle: { borderWidth: 0, backgroundColor: colors.surfaceSecondary }, aisleText: { fontSize: 9, color: colors.muted }, driver: { backgroundColor: colors.surfaceSecondary, borderColor: colors.borderStrong, borderStyle: 'dashed' }, ladies: { position: 'absolute', top: 1, right: 3, fontFamily: fonts.body, fontSize: 8, color: colors.brandSecondary }, legend: { flexDirection: 'row', justifyContent: 'center', gap: 10, paddingVertical: 8 } });