export type AdminField = { key: string; label: string; type?: 'number' | 'boolean' | 'select' | 'multiline' | 'password'; options?: string[]; placeholder?: string };
export const adminConfig: Record<string, { title: string; singular: string; icon: string; description: string; defaults: any; fields: AdminField[] }> = {
  buses: { title: 'Buses & layouts', singular: 'bus', icon: 'bus-outline', description: 'Your fleet. Configured down to the seat.', defaults: { name: '', number: '', operator: '', type: 'Seater', ac: true, amenities: '', active: true }, fields: [
    { key: 'name', label: 'Bus name', placeholder: 'e.g. Evening Express' }, { key: 'number', label: 'Registration number', placeholder: 'e.g. KA 01 AB 1234' }, { key: 'operator', label: 'Operator name' }, { key: 'type', label: 'Bus type', type: 'select', options: ['Seater', 'Sleeper', 'Seater + Sleeper'] }, { key: 'ac', label: 'Air conditioning', type: 'boolean' }, { key: 'amenities', label: 'Amenities · comma separated', placeholder: 'Charging point, Water, Wi-Fi' }, { key: 'active', label: 'Bus active', type: 'boolean' }] },
  routes: { title: 'Route network', singular: 'route', icon: 'git-branch-outline', description: 'Connect cities. Define every stop.', defaults: { source: '', destination: '', distance_km: '', duration_minutes: '', stops: '', boarding_points: '', dropping_points: '', active: true }, fields: [
    { key: 'source', label: 'Departure city' }, { key: 'destination', label: 'Destination city' }, { key: 'distance_km', label: 'Distance in kilometres', type: 'number' }, { key: 'duration_minutes', label: 'Journey duration in minutes', type: 'number' }, { key: 'stops', label: 'Intermediate stops · comma separated' }, { key: 'boarding_points', label: 'Boarding points · comma separated' }, { key: 'dropping_points', label: 'Dropping points · comma separated' }, { key: 'active', label: 'Route active', type: 'boolean' }] },
  staff: { title: 'Drivers & staff', singular: 'team member', icon: 'people-outline', description: 'The people who keep your network moving.', defaults: { name: '', email: '', mobile: '', password: '', role: 'driver', license: '' }, fields: [
    { key: 'name', label: 'Full name' }, { key: 'email', label: 'Email address' }, { key: 'mobile', label: 'Mobile number', placeholder: '+91 or 10-digit number' }, { key: 'password', label: 'Initial password · 12+ characters', type: 'password' }, { key: 'role', label: 'Account role', type: 'select', options: ['driver', 'admin'] }, { key: 'license', label: 'Driving license number' }] },
  trips: { title: 'Schedules & trips', singular: 'trip', icon: 'calendar-outline', description: 'Turn your fleet into bookable journeys.', defaults: { bus_id: '', route_id: '', driver_id: '', date: '', departure: '', convenience_fee: '0', published: false }, fields: [
    { key: 'bus_id', label: 'Bus', type: 'select' }, { key: 'route_id', label: 'Route', type: 'select' }, { key: 'driver_id', label: 'Assigned driver', type: 'select' }, { key: 'date', label: 'Journey date · YYYY-MM-DD', placeholder: 'YYYY-MM-DD' }, { key: 'departure', label: 'Departure · HH:MM (24-hour IST)', placeholder: '21:30' }, { key: 'convenience_fee', label: 'Convenience fee (₹) per reservation', type: 'number' }, { key: 'published', label: 'Publish for passenger search', type: 'boolean' }] },
  offers: { title: 'Offers & coupons', singular: 'offer', icon: 'pricetag-outline', description: 'Create something worth going further for.', defaults: { title: '', code: '', description: '', discount_percent: '', minimum_amount: '0', maximum_discount: '', valid_until: '', active: true }, fields: [
    { key: 'title', label: 'Offer title' }, { key: 'code', label: 'Coupon code · uppercase letters and numbers' }, { key: 'description', label: 'Offer details & terms', type: 'multiline' }, { key: 'discount_percent', label: 'Discount percentage', type: 'number' }, { key: 'minimum_amount', label: 'Minimum fare (₹)', type: 'number' }, { key: 'maximum_discount', label: 'Maximum discount (₹)', type: 'number' }, { key: 'valid_until', label: 'Valid until · YYYY-MM-DD' }, { key: 'active', label: 'Offer active', type: 'boolean' }] },
};