import { ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useResource } from '@/src/use-resource';
import { Screen, Header, Button, Card, Badge, Icon, Section, Loading, Notice, money, s } from '@/src/components/ui';
import { tripTime } from '@/src/components/trip-card';

export default function TripDetail() {
  const { id, count = '1' } = useLocalSearchParams<{ id: string; count?: string }>();
  const { data: trip, error, loading, refresh } = useResource(`/trips/${id}`, true);
  return <Screen><Header title="Your journey, in detail" back /><ScrollView contentContainerStyle={s.content}><Notice message={error} />{loading ? <Loading /> : trip && <><Card><View style={s.between}><Icon name="bus-outline" size={32} /><Badge title={`${trip.bus.ac ? 'AC' : 'Non-AC'} · ${trip.bus.type}`} /></View><Text style={s.h1}>{trip.bus.operator}</Text><Text style={s.body}>{trip.bus.name} · {trip.bus.number}</Text><View style={s.divider} /><View style={s.between}><View><Text style={s.h2}>{tripTime(trip.departure_at)}</Text><Text style={s.body}>{trip.route.source}</Text></View><Icon name="arrow-forward" /><View style={{ alignItems: 'flex-end' }}><Text style={s.h2}>{tripTime(trip.arrival_at)}</Text><Text style={s.body}>{trip.route.destination}</Text></View></View><Text style={s.caption}>{trip.date} · {trip.route.duration_minutes} minutes · {trip.route.distance_km} km</Text></Card><Section title="On board" /><Card>{trip.bus.amenities.length ? trip.bus.amenities.map((amenity: string) => <View key={amenity} style={s.row}><Icon name="checkmark-circle-outline" size={18} /><Text style={s.bodyStrong}>{amenity}</Text></View>) : <Text style={s.body}>No additional amenities listed by this operator.</Text>}</Card><Section title="Boarding & dropping points" /><Card><Text style={s.overline}>BOARD AT</Text>{trip.route.boarding_points.map((point: string) => <Text key={point} style={s.bodyStrong}>{point}</Text>)}<View style={s.divider} /><Text style={s.overline}>DROP AT</Text>{trip.route.dropping_points.map((point: string) => <Text key={point} style={s.bodyStrong}>{point}</Text>)}</Card>{trip.route.stops.length > 0 && <><Section title="Along the way" /><Card>{trip.route.stops.map((stop: string, i: number) => <View style={s.row} key={`${i}-${stop}`}><Icon name="location-outline" size={18} /><Text style={s.body}>{stop}</Text></View>)}</Card></>}</>}{error && <Button title="Try again" testID="retry-trip-detail-button" onPress={refresh} />}</ScrollView>{trip && <View style={s.footer}><View style={s.between}><Text style={s.body}>{trip.available_seats} seats available</Text><Text style={s.h2}>From {money(trip.from_price)}</Text></View><Button title="Choose your seats" testID="choose-seats-button" onPress={() => router.push({ pathname: '/seats/[id]', params: { id, count } })} /></View>}</Screen>;
}